## 如果jar 包运行 则开启以下配置
server:
  ## 设定编码
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  ## 指定访问项目路径的项目名
#  servlet:
#    context-path: /basicserver
  ## 引入thymeleaf模板
spring:
  ## 约定传参编码格式
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  thymeleaf:
    ## 在构建URL时预先查看名称的前缀
    prefix: classpath:/templates/
    ## 构建URL时附加查看名称的后缀    .html
    suffix: .html
    ## 关闭模板缓存
    cache: false
    ## 模板编码
    encoding: UTF-8
    servlet:
      content-type: text/html

  ## 静态资源路径配置
  resources:
    static-locations: classpath:/templates/,classpath:/static/